/* Generated by :claw at 2021-08-20T18:32:24.767915Z */

#if defined(__cplusplus)
#include <new>
#endif



#include "lib/SDL_platform.x86_64-pc-linux-gnu.h"
#include "SDL.h"
#include "SDL_syswm.h"

#if !defined(__CLAW_API)
#  if defined(_WIN32)
#    define __CLAW_API __declspec(dllexport)
#  elif defined(__GNUC__)
#    define __CLAW_API __attribute__((visibility("default")))
#  else
#    define __CLAW_API
#  endif
#endif

#if defined(__cplusplus)
extern "C" {
#endif


__CLAW_API Uint64 __claw_SDL_Swap64(Uint64 x) {
// /home/borodust/devel/repo/aw-projects/aw-sdl/src/lib/sdl/include/SDL_endian.h:192:1
return SDL_Swap64(x);
}

__CLAW_API SDL_GameControllerButtonBind* __claw_SDL_GameControllerGetBindForAxis(SDL_GameControllerButtonBind* __claw_result_, SDL_GameController* gamecontroller, SDL_GameControllerAxis axis) {
// /home/borodust/devel/repo/aw-projects/aw-sdl/src/lib/sdl/include/SDL_gamecontroller.h:338:1
(*__claw_result_) = SDL_GameControllerGetBindForAxis(gamecontroller, axis);
return __claw_result_;
}

__CLAW_API SDL_bool __claw_SDL_PointInRect(const SDL_Point* p, const SDL_Rect* r) {
// /home/borodust/devel/repo/aw-projects/aw-sdl/src/lib/sdl/include/SDL_rect.h:99:27
return SDL_PointInRect(p, r);
}

__CLAW_API void __claw_SDL_JoystickGetGUIDString(SDL_JoystickGUID* guid, char* pszGUID, int cbGUID) {
// /home/borodust/devel/repo/aw-projects/aw-sdl/src/lib/sdl/include/SDL_joystick.h:299:30
SDL_JoystickGetGUIDString(*guid, pszGUID, cbGUID);
}

__CLAW_API SDL_bool __claw_SDL_RectEquals(const SDL_Rect* a, const SDL_Rect* b) {
// /home/borodust/devel/repo/aw-projects/aw-sdl/src/lib/sdl/include/SDL_rect.h:116:27
return SDL_RectEquals(a, b);
}

__CLAW_API SDL_bool __claw_SDL_RectEmpty(const SDL_Rect* r) {
// /home/borodust/devel/repo/aw-projects/aw-sdl/src/lib/sdl/include/SDL_rect.h:108:27
return SDL_RectEmpty(r);
}

__CLAW_API Uint32 __claw_SDL_Swap32(Uint32 x) {
// /home/borodust/devel/repo/aw-projects/aw-sdl/src/lib/sdl/include/SDL_endian.h:125:1
return SDL_Swap32(x);
}

__CLAW_API SDL_GameControllerButtonBind* __claw_SDL_GameControllerGetBindForButton(SDL_GameControllerButtonBind* __claw_result_, SDL_GameController* gamecontroller, SDL_GameControllerButton button) {
// /home/borodust/devel/repo/aw-projects/aw-sdl/src/lib/sdl/include/SDL_gamecontroller.h:402:1
(*__claw_result_) = SDL_GameControllerGetBindForButton(gamecontroller, button);
return __claw_result_;
}

__CLAW_API Uint16 __claw_SDL_Swap16(Uint16 x) {
// /home/borodust/devel/repo/aw-projects/aw-sdl/src/lib/sdl/include/SDL_endian.h:81:1
return SDL_Swap16(x);
}

__CLAW_API char* __claw_SDL_GameControllerMappingForGUID(SDL_JoystickGUID* guid) {
// /home/borodust/devel/repo/aw-projects/aw-sdl/src/lib/sdl/include/SDL_gamecontroller.h:169:32
return SDL_GameControllerMappingForGUID(*guid);
}

__CLAW_API SDL_JoystickGUID* __claw_SDL_JoystickGetGUIDFromString(SDL_JoystickGUID* __claw_result_, const char* pchGUID) {
// /home/borodust/devel/repo/aw-projects/aw-sdl/src/lib/sdl/include/SDL_joystick.h:304:42
(*__claw_result_) = SDL_JoystickGetGUIDFromString(pchGUID);
return __claw_result_;
}

__CLAW_API SDL_JoystickGUID* __claw_SDL_JoystickGetDeviceGUID(SDL_JoystickGUID* __claw_result_, int device_index) {
// /home/borodust/devel/repo/aw-projects/aw-sdl/src/lib/sdl/include/SDL_joystick.h:151:42
(*__claw_result_) = SDL_JoystickGetDeviceGUID(device_index);
return __claw_result_;
}

__CLAW_API float __claw_SDL_SwapFloat(float x) {
// /home/borodust/devel/repo/aw-projects/aw-sdl/src/lib/sdl/include/SDL_endian.h:216:1
return SDL_SwapFloat(x);
}

__CLAW_API SDL_JoystickGUID* __claw_SDL_JoystickGetGUID(SDL_JoystickGUID* __claw_result_, SDL_Joystick* joystick) {
// /home/borodust/devel/repo/aw-projects/aw-sdl/src/lib/sdl/include/SDL_joystick.h:263:42
(*__claw_result_) = SDL_JoystickGetGUID(joystick);
return __claw_result_;
}

#if defined(__cplusplus)
}
#endif
