name: Build
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  Build:
    runs-on: ubuntu-18.04
    steps:
      - name: Check Out Everything
        id: checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install LLVM And Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "9.0"
      - name: Install Required Packages
        run: >-
          sudo apt-get update && sudo apt-get install -y
          libdbus-1-dev libibus-1.0-dev libudev-dev
          libegl1-mesa-dev libgl1-mesa-dev libgles2-mesa-dev
          libwayland-dev
          libx11-dev libxcursor-dev libxext-dev libxi-dev libxinerama-dev libxkbcommon-dev
          libxrandr-dev libxt-dev libxv-dev libxxf86vm-dev
      - name: Build Binaries
        run: |
          cd ${{ github.workspace }}/src/lib/ && ./build.sh desktop
      - name: Publish Binaries
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            src/lib/build/desktop/libsdl2.clawed.so
            src/lib/build/desktop/libSDL2-2.0.so.0
