name: Build
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Check Out Everything
        id: checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Build Variables
        id: vars
        run: >-
          export RELEASE_VERSION=${GITHUB_REF#refs/*/} &&
          echo ::set-output name=runtime_binary::libsdl2.clawed-linux-x86_64-$RELEASE_VERSION.so
      - name: Install LLVM And Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "9.0"
      - name: Install Required Packages
        run: >-
          sudo apt-get update && sudo apt-get install -y
          libdbus-1-dev libibus-1.0-dev libudev-dev
          libegl1-mesa-dev libgl1-mesa-dev libgles2-mesa-dev
          libwayland-dev
          libx11-dev libxcursor-dev libxext-dev libxi-dev libxinerama-dev libxkbcommon-dev
          libxrandr-dev libxt-dev libxv-dev libxxf86vm-dev
      - name: Build Binaries
        run: |
          cd ${{ github.workspace }}/src/lib/ && ./build.sh desktop
      - name: Rename Binaries
        run: >-
          mv src/lib/build/desktop/libsdl2.clawed.so ${{ steps.vars.outputs.runtime_binary }}
      - name: Publish Binaries
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ${{ steps.vars.outputs.runtime_binary }}
            src/lib/build/desktop/libSDL2-2.0.so.0
  build-windows:
    runs-on: windows-2019
    steps:
      - name: Check Out Everything
        id: checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Build Variables
        id: vars
        run: >-
          export RELEASE_VERSION=${GITHUB_REF#refs/*/} &&
          echo ::set-output name=runtime_binary::sdl2.clawed-windows-x64-$RELEASE_VERSION.dll
        shell: bash
      - name: Build Binaries
        run: |
          cd ${{ github.workspace }}/src/lib/
          ./build.ps1
        shell: pwsh
      - name: Rename Binaries
        run: >-
          mv src/lib/build/desktop/sdl2.clawed.dll ${{ steps.vars.outputs.runtime_binary }}
      - name: Publish Binaries
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ${{ steps.vars.outputs.runtime_binary }}
            src/lib/build/desktop/SDL2.dll
  build-android:
    runs-on: ubuntu-20.04
    steps:
      - name: Check Out Everything
        id: checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Build Variables
        id: vars
        run: >-
          export RELEASE_VERSION=${GITHUB_REF#refs/*/} &&
          echo ::set-output name=ndk_version::22.1.7171670 &&
          echo ::set-output name=runtime_binary::libsdl2.clawed-android-aarch64-$RELEASE_VERSION.so
      - name: Install Required Packages
        run: >-
          sudo apt-get update && sudo apt-get install -y
          libdbus-1-dev libibus-1.0-dev libudev-dev
          libegl1-mesa-dev libgl1-mesa-dev libgles2-mesa-dev
          libwayland-dev
          libx11-dev libxcursor-dev libxext-dev libxi-dev libxinerama-dev libxkbcommon-dev
          libxrandr-dev libxt-dev libxv-dev libxxf86vm-dev
      - name: Cache NDK
        id: cache-ndk
        uses: actions/cache@v2
        with:
          path: |
            $ANDROID_HOME/ndk/${{ steps.vars.outputs.ndk_version }}/
          key: ndk-${{ steps.vars.outputs.runtime_binary }}
      - name: Install Required NDK version
        run: sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;${{ steps.vars.outputs.ndk_version }}"
      - name: Build Binaries
        run: >-
          cd ${{ github.workspace }}/src/lib/ &&
          ./build.sh --arch aarch64 --ndk $ANDROID_HOME/ndk/${{ steps.vars.outputs.ndk_version }}
          android
      - name: Rename Binaries
        run: >-
          mv src/lib/build/android/libsdl2.clawed.so ${{ steps.vars.outputs.runtime_binary }}
      - name: Publish Binaries
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ${{ steps.vars.outputs.runtime_binary }}
            src/lib/build/android/sdl/libSDL2.so
